# Generated by Django 2.2.6 on 2019-10-30 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=70, null=True, unique=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=150)),
                ('date_pub', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
