# Generated by Django 2.2.6 on 2019-10-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobj',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
