# Generated by Django 2.2.6 on 2019-12-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191031_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobj',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
